name=TinySparse
version=1.0.0
author=Pranesh S A
maintainer=Pranesh S A
sentence=A bare-metal sparse neural network acceleration library for edge microcontrollers.
paragraph=TinySparse optimizes matrix multiplications by skipping zero-valued weights and activations, drastically reducing inference latency and power consumption on devices like the ESP32-S3.
category=Data Processing
url=https://github.com/pranesh-eca/TinySparse
architectures=*